name: Android CI

on:
  push:
    branches: [ "develop" ]
  pull_request:
    branches: [ "develop" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        cache: gradle

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Build with Gradle
      run: ./gradlew build
    - name: 检测当前文件夹
      run: ls
    - name: 检测app文件夹
      run: ls app
    - name: 检测build文件夹
      run: ls app/build
    - name: 检测outputs文件夹
      run: ls app/build/outputs
    - name: 检测apk文件夹
      run: ls app/build/ooutputs/apk
    - name: Upload APK
      uses: actions/upload-artifact@v3
      with:
          name: apk
          path: app/build/outputs/app-release.apk
